# Generated by Django 3.2.25 on 2024-10-31 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia', models.CharField(max_length=50)),
                ('metodo_de_pago', models.CharField(choices=[(1, 'Mecado Pago'), (2, 'Cuenta DNI'), (3, 'Efectivo')], max_length=50)),
            ],
        ),
    ]
