# Generated by Django 3.2.25 on 2024-10-31 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasto',
            name='monto',
            field=models.IntegerField(default=0),
        ),
    ]
